version: "3"

services:

  # setup database
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssw()rd
    ports:
      - 1433:1433
