// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>

using Infra.OAuth.AspNetCore;
using Infra.OAuth.Authentication;
using Infra.OAuth.Settings;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Infra.OAuth.DependencyInjection
{
  public static class AddOAuthGenericAuthenticationExtensions
  {
    public static IOAuthBuilder AddOAuthGenericAuthentication(this IServiceCollection services, IConfiguration configuration)
    {
      services.AddScoped<IOAuthSettingsFactory>(sp => new OAuthSettingsFactory(configuration));

      services.AddScoped<IOAuthAuthentication, OAuthAuthentication>();

      services.AddAuthentication(options =>
      {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
      })
      .AddScheme<TokenAuthenticationOptions, GenericAuthenticationHandler>(JwtBearerDefaults.AuthenticationScheme, null);

      return new OAuthBuilder(services);
    }
  }
}
